export const SET_REPOSITORIES = 'SET_REPOSITORIES';
export const SET_CURRENT_REPOSITORY = 'SET_CURRENT_REPOSITORY';

export const SET_DIRECTORY_CONTENT = 'SET_DIRECTORY_CONTENT';
export const SET_DIRECTORY_PATH = 'SET_DIRECTORY_PATH';

export const SET_FILE_DATA = 'SET_FILE_DATA';
export const CLEAR_FILE_DATA = 'CLEAR_FILE_DATA';